"use strict";
exports.__esModule = true;
var DoSomething_1 = require("./DoSomething");
var DoSomething_2 = require("./DoSomething");
var DoSomething_3 = require("./DoSomething");
DoSomething_1.play(DoSomething_1.Instrument.Piano);
DoSomething_2.testMap();
console.log(DoSomething_3["default"]([3, 8, 12, 2], 11));
DoSomething_1.play(DoSomething_1.Instrument.Violin);
DoSomething_2.testMap();
console.log(DoSomething_3["default"]([3, 8, 12, 2], 11));
DoSomething_1.play(DoSomething_1.Instrument.Guitar);
DoSomething_2.testMap();
console.log(DoSomething_3["default"]([3, 8, 12, 2], 11));
DoSomething_1.play(DoSomething_1.Instrument.Cello);
DoSomething_2.testMap();
console.log(DoSomething_3["default"]([3, 8, 12, 2], 11));
